branch-defaults:
  master:
    environment: broadway-delicatessen-env
    group_suffix: null
environment-defaults:
  broadway-delicatessen-env:
    branch: null
    repository: null
global:
  application_name: broadway_delicatessen
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
